name: TAD_Character_Wizard
version: '${project.version}'
main: jp.houlab.mochidsuki.tad_character_wizard.TAD_Character_Wizard
api-version: '1.20'

commands:
  tcw:
    description: "TAD Character Wizard command for debug"
    usage: "/command <arg>"
    aliases: [tadcharacterwizard]
    permission: TAD_Character_Wizard.command.tcw
    permission-message: "You do not have permission to use this command"
